# Portafoglio Stonks

L'Azienda degli Ingegneri Matematici ha licenziato il dipendente che ha composto il precedente portafoglio e ora è il tuo compito scegliere le azioni che faranno stonks! Il Responsabile dei finanziamenti Dott. Alex Monte Carlo Money ti concede 1.000.000€ di capitale da investire.

1. [1pt] Importa il file "stonks.csv" come dataframe di pandas, esso contiene i prezzi giornalieri delle azioni di 16 società convertiti in euro dal 1 Gennaio 2016. Salvalo in un dataframe e visualizzalo tramite i metodi head, tail, describe, info

In [1]:
import pandas as pd

stonk = pd.read_csv('stonks.csv', header = 0)
stonk.head()

,Date,Alphabet Inc- A shares (GOOGL),Amazon.com Inc (AMZN),Facebook Inc (FB),Microsoft Corp (MSFT),TESLA Inc.,Morgan Stanley (MS),Ferrari N.V. (RACE.MI),Assicurazioni Generali S.p.A. (G.MI),Juventus Football Club S.p.A. (JUVE.MI),Piaggio & C. SpA (PIA.MI),Toscana Aeroporti S.p.A. (TYA.MI),Valsoia S.p.A. (VLS.MI),Bayer Aktiengesellschaft (BAYN.DE),Ryanair Holdings plc (RY4C.IR),Crdit Agricole S.A. (ACA.PA),"Cisco Systems, Inc. (CSCO)"
0,4-Jan-16,699.68740,586.87173,94.17735,46.19284,41.16643,25.6297,41.73360,11.8179,0.23926,1.8482,13.0030,17.7484,92.23299,14.865,8.14874,20.8776
1,5-Jan-16,703.32626,585.34939,94.87835,46.51689,41.27065,25.5291,42.61280,11.9419,0.24074,1.8007,12.8028,17.9230,92.39927,15.010,8.18324,20.8334
2,6-Jan-16,706.22277,588.40273,95.76832,45.99285,40.74408,25.0674,42.62236,11.7157,0.24230,1.7598,12.9073,17.6872,91.06999,15.340,7.98754,20.7564
3,7-Jan-16,687.44782,564.00408,90.84330,44.28186,40.01299,23.7585,41.23666,11.6938,0.23945,1.6927,13.0117,17.4166,88.74484,14.740,7.79191,20.2268
4,8-Jan-16,668.96514,555.60232,89.08126,43.82015,38.62354,22.9536,38.74239,11.5698,0.23945,1.6452,12.6723,18.3420,86.29394,14.965,7.68449,19.4599

In [2]:
list(stonk)

['Date',
 'Alphabet Inc- A shares (GOOGL)',
 'Amazon.com Inc (AMZN)',
 'Facebook Inc (FB)',
 'Microsoft Corp (MSFT)',
 'TESLA Inc.',
 'Morgan Stanley (MS)',
 'Ferrari N.V. (RACE.MI)',
 'Assicurazioni Generali S.p.A. (G.MI)',
 'Juventus Football Club S.p.A. (JUVE.MI)',
 'Piaggio & C. SpA (PIA.MI)',
 'Toscana Aeroporti S.p.A. (TYA.MI)',
 'Valsoia S.p.A. (VLS.MI)',
 'Bayer Aktiengesellschaft (BAYN.DE)',
 'Ryanair Holdings plc (RY4C.IR)',
 'Cr\x82dit Agricole S.A. (ACA.PA)',
 'Cisco Systems, Inc. (CSCO)']

In [3]:
stonk.tail()

,Date,Alphabet Inc- A shares (GOOGL),Amazon.com Inc (AMZN),Facebook Inc (FB),Microsoft Corp (MSFT),TESLA Inc.,Morgan Stanley (MS),Ferrari N.V. (RACE.MI),Assicurazioni Generali S.p.A. (G.MI),Juventus Football Club S.p.A. (JUVE.MI),Piaggio & C. SpA (PIA.MI),Toscana Aeroporti S.p.A. (TYA.MI),Valsoia S.p.A. (VLS.MI),Bayer Aktiengesellschaft (BAYN.DE),Ryanair Holdings plc (RY4C.IR),Crdit Agricole S.A. (ACA.PA),"Cisco Systems, Inc. (CSCO)"
1262,9-Nov-20,1481.0549,2643.3510,234.3982,183.6289,354.2081,47.1033,178.55,13.160,0.7576,2.420,14.00,13.45,46.175,15.19,8.450,32.1197
1263,10-Nov-20,1469.2424,2566.1097,230.3396,178.4090,346.9594,47.1366,173.10,13.470,0.7774,2.434,13.35,13.50,47.590,15.35,8.848,32.7378
1264,11-Nov-20,1478.3493,2654.5779,233.9326,183.2252,352.9380,47.6699,177.45,13.480,0.7842,2.492,12.95,13.40,48.095,15.46,8.756,33.2775
1265,12-Nov-20,1479.4360,2640.2384,233.5085,182.8816,349.5327,47.1550,176.35,13.460,0.7850,2.468,13.00,14.00,47.470,15.22,8.544,32.8260
1266,13-Nov-20,1501.4839,2650.7724,234.6360,183.4303,346.0870,47.9608,174.50,13.635,0.7792,2.558,13.70,13.80,47.690,15.07,8.630,35.0747

In [4]:
stonk.describe()

,Alphabet Inc- A shares (GOOGL),Amazon.com Inc (AMZN),Facebook Inc (FB),Microsoft Corp (MSFT),TESLA Inc.,Morgan Stanley (MS),Ferrari N.V. (RACE.MI),Assicurazioni Generali S.p.A. (G.MI),Juventus Football Club S.p.A. (JUVE.MI),Piaggio & C. SpA (PIA.MI),Toscana Aeroporti S.p.A. (TYA.MI),Valsoia S.p.A. (VLS.MI),Bayer Aktiengesellschaft (BAYN.DE),Ryanair Holdings plc (RY4C.IR),Crdit Agricole S.A. (ACA.PA),"Cisco Systems, Inc. (CSCO)"
count,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000,1267.000000
mean,952.873876,1329.187111,149.086545,92.465773,78.299876,35.847289,99.449367,12.768368,0.772117,1.924858,14.045375,13.514710,75.028224,13.501167,10.019952,32.814227
std,206.954756,608.375581,34.854375,43.205935,76.950496,7.151741,40.785324,2.465733,0.388423,0.419766,1.441010,2.368485,15.627431,2.478410,2.091885,8.039017
min,605.086550,430.811610,86.456680,39.802000,25.450860,17.091300,26.758430,7.588540,0.212740,1.205100,9.600000,7.503600,40.360000,8.322000,5.820370,17.107400
25%,791.054870,801.945320,123.611550,57.567255,42.281455,34.664350,62.155795,11.272600,0.413415,1.553550,13.159100,11.500000,61.128435,11.575000,8.126000,25.179450
50%,928.235560,1345.001900,145.213200,82.698150,52.733370,37.160200,98.295360,12.755000,0.746430,1.936200,13.750000,13.914800,76.231670,13.455000,10.328300,33.410000
75%,1084.909100,1652.040700,169.083750,122.561400,61.032375,40.492700,138.861000,13.773950,1.122650,2.292100,14.430800,15.082150,87.748530,15.402500,11.713400,39.544550
max,1502.214300,2961.828200,256.788800,194.284900,418.115400,50.970700,178.550000,18.723700,1.571100,2.907700,18.650000,19.363400,107.656200,19.385000,13.650000,49.414800

In [5]:
stonk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 17 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Date                                     1267 non-null   object
 1   Alphabet Inc- A shares (GOOGL)           1267 non-null   float64
 2   Amazon.com Inc (AMZN)                    1267 non-null   float64
 3   Facebook Inc (FB)                        1267 non-null   float64
 4   Microsoft Corp (MSFT)                    1267 non-null   float64
 5   TESLA Inc.                               1267 non-null   float64
 6   Morgan Stanley (MS)                      1267 non-null   float64
 7   Ferrari N.V. (RACE.MI)                   1267 non-null   float64
 8   Assicurazioni Generali S.p.A. (G.MI)     1267 non-null   float64
 9   Juventus Football Club S.p.A. (JUVE.MI)  1267 non-null   float64
 10  Piaggio & C. SpA (PIA.MI)                1267 non-null   float64
 11  Toscana Aeroporti S.p.A. (TYA.MI)        1267 non-null   float64
 12  Valsoia S.p.A. (VLS.MI)                  1267 non-null   float64
 13  Bayer Aktiengesellschaft (BAYN.DE)       1267 non-null   float64
 14  Ryanair Holdings plc (RY4C.IR)           1267 non-null   float64
 15  Crdit Agricole S.A. (ACA.PA)            1267 non-null   float64
 16  Cisco Systems, Inc. (CSCO)               1267 non-null   float64
dtypes: float64(16), object(1)
memory usage: 168.4+ KB

2. [1pt] Scrivi una funzione che consenta di visualizzare il grafico dell'andamento del prezzo di un'azione, possibilmente in un intervallo di tempo compreso tra due date

3. [1pt] Converti il dataframe in numpy, calcola i ritorni giornalieri (prezzo_giorno_successivo/prezzo_giorno_precendete - 1) e visualizzali in 16 plot diversi

4. [1pt] Rispetto ai ritorni, calcola la media, deviazione standard, le correlazioni. 

Quale azione ha ritorni medi maggiori da inizio Gennaio 2016 ad ora? Qual è la più volatile (maggiore deviazione standard)?\
Quale azione ha ritorni medi maggiori da inizio Gennaio 2020 ad ora? Qual è la più volatile (maggiore deviazione standard)?

In [ ]:
# ...

5. [1pt] Un portafoglio è un insieme di assets, ad esempio:

GOOGL 3 azioni\
AMZN 4 azioni\
FB 5 azioni

Il valore del portafoglio è 3 * prezzo di GOOGL + 4 * prezzo di AMZN + 5 * prezzo di FB

Costruisci il portafoglio che fa stonks nel 2020, ovvero che, se costruito il 01/01/2020 con 1000000€, ad oggi avrebbe il maggior valore, con le seguenti condizioni:

- all'inizio in ogni società non puoi investire più di 200000€ (20%)
- il numero di azioni acquistate di ogni società deve essere un intero non negativo
- non ci sono tassi di interesse, dividendi, commissioni e simili
- bisogna investire almeno il 99% della liquidità, la rimenente non verrà considerat

In [ ]:
# Esempio di portafoglio:

portfolio_test = pd.DataFrame(data={'Code': ["GOOGL","AMZN","FB"], 'NumStocks': [3,4,5],
                                    'Value 01/01/20': [1193.6639,1646.7944,182.9187],
                                    'Value 13/11/20': [1501.4839,2650.7724,234.636]})

print(portfolio_test)

# ...

    Code  NumStocks  Value 01/01/20  Value 13/11/20
0  GOOGL          3       1193.6639       1501.4839
1   AMZN          4       1646.7944       2650.7724
2     FB          5        182.9187        234.6360

FACOLTATIVO PER BONUS: Costruisci ad oggi il portafoglio che avrebbe la migliore performance al 31/12/2020 (implementa la tua strategia preferita)